# -----------------------------------------------------------------------------
# JoEmbedded Basis build configuration
#
# This file is the base configuration (primary prj.conf).
# It mainly provides the MAIN-JESFS-Shell framework and the tb_xxxx toolbox.

# -----------------------------------------------------------------------------
# DEBUG BUILD (clearly visible here, but better to enable in Kconfig-Menue)
# Enables debug information for better source-level debugging.
# Note: This reduces optimizations and can increase Flash/RAM usage.
# For non-debug/release builds, just add a '#' in front of these lines.
# -----------------------------------------------------------------------------
# CONFIG_DEBUG_OPTIMIZATIONS=y
# CONFIG_DEBUG_THREAD_INFO=y

# -----------------------------------------------------------------------------
# Logging / UART
# UART needs about 170uA when enabled.
# Enable only if logging is needed: CONFIG_LOG=y
# -----------------------------------------------------------------------------
CONFIG_SERIAL=y
CONFIG_UART_CONSOLE=y

# -----------------------------------------------------------------------------
# Floating Point
# -----------------------------------------------------------------------------
# Floating Point Unit is generally useful
CONFIG_FPU=y
CONFIG_CBPRINTF_FP_SUPPORT=y

# -----------------------------------------------------------------------------
# Power Management
# -----------------------------------------------------------------------------
# Enables the power management API for hardware devices.
CONFIG_PM=y
CONFIG_PM_DEVICE=y
CONFIG_PM_DEVICE_RUNTIME=y
# Enables runtime PM by default for all drivers that support it.
CONFIG_PM_DEVICE_RUNTIME_DEFAULT_ENABLE=y

# -----------------------------------------------------------------------------
# Hardware ID
# -----------------------------------------------------------------------------
# Required for simple MAC handling: HWINFO (the library itself is not needed here)
CONFIG_HWINFO=y

# -----------------------------------------------------------------------------
# Memory
# -----------------------------------------------------------------------------
# CONFIG_MAIN_STACK_SIZE used to be smaller (4k),
# increased slightly for safety so local buffers (250 bytes) are safe.
CONFIG_MAIN_STACK_SIZE=6144
CONFIG_HEAP_MEM_POOL_SIZE=2048
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=2048

# -----------------------------------------------------------------------------
# MODULES
# -----------------------------------------------------------------------------

# -----------------------------------------------------------------------------
# MODULE BLuetooth UART
# -----------------------------------------------------------------------------
CONFIG_BLUETOOTH_UART=n


# -----------------------------------------------------------------------------
# MODULE JesFs with Shell
# -----------------------------------------------------------------------------
CONFIG_JESFS_SHELL=y

CONFIG_FLASH=y
CONFIG_SPI=y
CONFIG_SPI_NOR=y
CONFIG_CRC=y
# On MX25R6435F:65k and 4k pages possible, JesFs needs 4k page size
CONFIG_SPI_NOR_FLASH_LAYOUT_PAGE_SIZE=4096

# Optionally enable if flash should be scanned actively (SFDP data)
CONFIG_FLASH_JESD216_API=y
CONFIG_SPI_NOR_SFDP_RUNTIME=y





